### ISSUE TITLE
cannot get the example to run on Win 10 cmd.

### ISSUE THREAD

**Issue by beluchin** [ruedigergad/cli4clj#2]
hello, this appears to be a very useful tool for my project but I failed to get it to work on the very first try. When running `lein run` I got the first prompt but then it would not respond to any commands:

    > lein run
    Reflection warning, C:\...\form-init8532592205835804337.clj:1:889 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
    cli#

    Terminate batch job (Y/N)? y

What may I be missing?

Thanks.

**Comment by beluchin** [comment]
nvm - I managed to get this to work by registering the UnsupportedTerminal for the WINDOWS flavor

**Comment by ruedigergad** [comment]
Hi,
thanks a lot for the bug report and even finding a workaround. :)
I just implemented your workaround for Windows and uploaded cli4clj version 1.7.3 to Clojars.
I hope this fixes the issue for all Windows users.
Cheers,
Ruediger

**Comment by ruedigergad** [comment]
Just to keep the information in one place:
I made a silly mistake that is now fixed and version 1.7.4 should finally fix the Windows issue.
