### ISSUE TITLE
EOF needs to optionally quit

### ISSUE THREAD

**Issue by dgr** [ruedigergad/cli4clj#3]
Right now, pressing Ctl-D on MacOS doesn't shut down a CLI application based on cli4clj as with most other MacOS command line apps. There probably needs to be an option in cli4clj that will optionally detect EOF and return as if "q" had been entered into the CLI.

**Comment by ruedigergad** [comment]
Thanks a lot for reporting the issue!
I could reproduce it on Linux here and fix it at least here. I uploaded version 1.7.6 to Clojars and as standalone jar.
I hope this solves the problem for you as well. If I don't get any feedback for some days, I will consider this as fixed and close the issue.
Cheers, Ruediger
